#!/usr/bin/env bash
# Hydra Wall Street Library — interactive .env writer.
# Prompts for Alpaca paper credentials, writes .env with mode 0600, and verifies
# the keys with a single GET /v2/account against paper-api.alpaca.markets.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$ROOT_DIR/.env"
EXAMPLE_FILE="$ROOT_DIR/.env.example"

if [[ ! -f "$EXAMPLE_FILE" ]]; then
  echo "missing .env.example next to setup-env.sh" >&2
  exit 1
fi

if [[ -f "$ENV_FILE" ]]; then
  read -r -p ".env already exists. Overwrite? [y/N] " confirm
  case "$confirm" in
    y|Y|yes|YES) ;;
    *) echo "aborted; existing .env left unchanged"; exit 0 ;;
  esac
fi

read -r -p "Alpaca paper APCA_API_KEY_ID: " key_id
if [[ -z "$key_id" ]]; then
  echo "key id is required" >&2
  exit 1
fi

# -s: silent so secret never echoes / lands in history
read -r -s -p "Alpaca paper APCA_API_SECRET_KEY: " secret
echo
if [[ -z "$secret" ]]; then
  echo "secret is required" >&2
  exit 1
fi

read -r -p "Use Alpaca paper endpoints? [Y/n] " paper_choice
case "$paper_choice" in
  n|N|no|NO) paper="false" ;;
  *) paper="true" ;;
esac

read -r -p "Hydra host [127.0.0.1]: " hydra_host
hydra_host="${hydra_host:-127.0.0.1}"
read -r -p "Hydra port [4001]: " hydra_port
hydra_port="${hydra_port:-4001}"
read -r -p "Hydra secure (wss/https)? [y/N] " hydra_secure_choice
case "$hydra_secure_choice" in
  y|Y|yes|YES) hydra_secure="true" ;;
  *) hydra_secure="false" ;;
esac

umask 077
{
  echo "# Generated by scripts/setup-env.sh on $(date -u +%FT%TZ)"
  echo "APCA_API_KEY_ID=$key_id"
  echo "APCA_API_SECRET_KEY=$secret"
  echo "ALPACA_PAPER=$paper"
  echo "HYDRA_HOST=$hydra_host"
  echo "HYDRA_PORT=$hydra_port"
  echo "HYDRA_SECURE=$hydra_secure"
  echo "HYDRA_HISTORY=yes"
} > "$ENV_FILE"
chmod 600 "$ENV_FILE"

echo "wrote $ENV_FILE (mode 600)"

base="https://paper-api.alpaca.markets"
if [[ "$paper" == "false" ]]; then
  base="https://api.alpaca.markets"
fi

if command -v curl >/dev/null 2>&1; then
  echo "verifying with $base/v2/account ..."
  status=$(curl -s -o /dev/null -w "%{http_code}" \
    -H "APCA-API-KEY-ID: $key_id" \
    -H "APCA-API-SECRET-KEY: $secret" \
    "$base/v2/account" || true)
  if [[ "$status" == "200" ]]; then
    echo "Alpaca account check: ok"
  else
    echo "Alpaca account check: HTTP $status (review keys / network)"
  fi
else
  echo "curl not found; skipping verification"
fi
